version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install coverage
  build:
    commands:
      - coverage run -m pytest
      - coverage report -m
      - coverage xml
  post_build:
    commands:
      - echo "Build completed!"
artifacts:
  files:
    - coverage.xml
    - **/*.py
