version: "3.8"

services:
  main-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-service
    ports:
      - "8002:8000" # Porta mapeada (localhost:8002 -> container:8000)
    environment:
      DATABASE_URL: "postgresql://admin:password123@db:5432/main_service_db"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: main-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: main_service_db
    ports:
      - "5434:5432" # Porta do PostgreSQL para o serviço
    volumes:
      - main-service-db-data:/var/lib/postgresql/data

volumes:
  main-service-db-data:
